Alternative tower for fast pairings
cloudflare/circl pull request #278
Opened 2021-09-14 00:15 UTC by wbl

By constructing Fp12 as a cubic over a biquadratic, we can take
advantage of the special form of line function evaluations and save
multiplications inside of the Miller loop. Currently this produces a
6% gain, although further improvements should be possible.

2021-09-18 01:48 UTC, armfazh requested changes
Minor changes.
Also we can rename F12Alt as `Fp12_3x4` or `Fp12_Fp4`

2021-09-18 01:48 UTC, armfazh commented on ecc/bls12381/ff/fp4.go
> +const Fp4Size = 4 * FpSize
```suggestion
const Fp4Size = 2 * Fp2Size
```

2021-09-18 01:48 UTC, armfazh commented on ecc/bls12381/ff/fp4.go
> +func (z *Fp4) MulSubfield(x *Fp4, y *Fp2) {
MulSubfield and MulT can be private functions, as only used in this package.

2021-09-18 01:48 UTC, armfazh commented on ecc/bls12381/ff/fp4.go
> +	return errFirst(z[0].SetBytes(x[0:Fp2Size]), z[1].SetBytes(x[Fp2Size:]))
Both Fp4 and F12Alt are never serialized so get can remove Bytes and SetBytes.

2021-09-21 15:03 UTC, bwesterb approved these changes
Looks good.  I checked everything except for MulLine, of which I couldn't quickly figure out how it works.  Please add some comment that show how you perform the computation.

2021-09-21 15:03 UTC, bwesterb commented on ecc/bls12381/ff/fp12alt.go
> +func (z *Fp12Alt) MulLine(x *Fp12Alt, y *LineValue) {
Please explain what's going on — I couldn't figure it out in 5 minutes.

2021-09-21 15:41 UTC, bwesterb commented
> > Minor changes.
> > Also we can rename F12Alt as `Fp12_3x4` or `Fp12_Fp4`
> 
> Neither of those fit go style. We could do Fp12Cubic?

I think `Fp12Alt` is just fine.

2021-09-21 16:39 UTC, armfazh approved these changes

2021-09-21 16:39 UTC, merged