group: removes order method from group interface
cloudflare/circl pull request #356
Opened 2022-07-29 22:14 UTC by armfazh

There is no point in returning a `Scalar` for Order method.
Also, returning a big.Int is not desirable.
Since the group order is public and well-know for the groups supported, then it's better to remove the method.

Based on top of: #355  (merge that first)
Fixes #214

2022-07-30 08:52 UTC, bwesterb approved these changes

2022-08-01 11:03 UTC, chris-wood requested changes
> Since the group order is public and well-know for the groups supported, then it's better to remove the method.

This is _precisely_ why we want to keep the function on the Group interface. Applications should not need to bake this into their code, possibly getting it wrong. (I could see them confusing the underlying field order with the group's order, for example.) They should just call the `Order` function on the desired group's interface.

2022-08-01 12:27 UTC, bwesterb commented
> They should just call the `Order` function on the desired group's interface.

The current `Order` function is broken because it uses `Scalar`.

I think it's bad to return a `big.Int`.

Let's step back: for what reasons would the user need the order and can we provide functions directly for those use-cases instead?

2022-08-01 12:33 UTC, chris-wood commented
> I think it's bad to return a big.Int.

Say more?

> Let's step back: for what reasons would the user need the order and can we provide functions directly for those use-cases instead?

The existing use cases we have are for determining scalar validity during deserialization, but that should already be covered by the deserialize functions on the Scalar interface. I don't know of any other uses, but as above, I don't think it's a good idea to punt this to applications should they need to use it for something we've not considered.

2022-08-01 15:13 UTC, bwesterb commented
> Say more?

Operations on `big.Int` are not constant time. We can add it, but then we need to add some very explicit warnings.

2022-12-04 17:46 UTC, bytemare commented
One use case: some app doesn't implement itself any group, and uses this package, but reimplements hash-to-scalar. The app doesn't have all the parameters of the group it handles, only abstractions, so it's useful for that app to get the order from the interface.

2024-01-03 12:04 UTC, bwesterb commented
What is your preference on how to proceed @armfazh ?

2024-01-23 00:26 UTC, armfazh commented
> What is your preference on how to proceed @armfazh ?

I have updated this PR to remove the `Order` method from the `Group` interface.

2024-01-23 01:52 UTC, merged